/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using CardLang.node;

namespace CardLang.analysis {


public interface Analysis : Switch
{
    Object GetIn(Node node);
    void SetIn(Node node, Object inobj);
    Object GetOut(Node node);
    void SetOut(Node node, Object outobj);

    void CaseStart(Start node);
    void CaseAProgramProgram(AProgramProgram node);
    void CaseAStatementCard(AStatementCard node);
    void CaseAReturnCard(AReturnCard node);
    void CaseAStopCard(AStopCard node);
    void CaseAExpressionCard(AExpressionCard node);
    void CaseAIfStatement(AIfStatement node);
    void CaseAIfElseStatement(AIfElseStatement node);
    void CaseAWhileStatement(AWhileStatement node);
    void CaseARepeatStatement(ARepeatStatement node);
    void CaseADamageStatement(ADamageStatement node);
    void CaseAHealStatement(AHealStatement node);
    void CaseAPullStatement(APullStatement node);
    void CaseARechargeStatement(ARechargeStatement node);
    void CaseARunStatement(ARunStatement node);
    void CaseAInsertStatement(AInsertStatement node);
    void CaseAAddExpression(AAddExpression node);
    void CaseASubExpression(ASubExpression node);
    void CaseAMulExpression(AMulExpression node);
    void CaseADivExpression(ADivExpression node);
    void CaseAModExpression(AModExpression node);
    void CaseARandomExpression(ARandomExpression node);
    void CaseANumberExpression(ANumberExpression node);
    void CaseAIdentifierExpression(AIdentifierExpression node);

    void CaseTCollect(TCollect node);
    void CaseTIf(TIf node);
    void CaseTElse(TElse node);
    void CaseTWhile(TWhile node);
    void CaseTRepeat(TRepeat node);
    void CaseTStart(TStart node);
    void CaseTEnd(TEnd node);
    void CaseTReturn(TReturn node);
    void CaseTDamage(TDamage node);
    void CaseTHeal(THeal node);
    void CaseTPull(TPull node);
    void CaseTRecharge(TRecharge node);
    void CaseTRun(TRun node);
    void CaseTInsert(TInsert node);
    void CaseTStop(TStop node);
    void CaseTRandom(TRandom node);
    void CaseTIdentifier(TIdentifier node);
    void CaseTName(TName node);
    void CaseTNumber(TNumber node);
    void CaseTPlus(TPlus node);
    void CaseTMinus(TMinus node);
    void CaseTTimes(TTimes node);
    void CaseTDiv(TDiv node);
    void CaseTMod(TMod node);
    void CaseTLessOrEqual(TLessOrEqual node);
    void CaseTGreaterOrEqual(TGreaterOrEqual node);
    void CaseTEquals(TEquals node);
    void CaseTNotEquals(TNotEquals node);
    void CaseTNot(TNot node);
    void CaseTLess(TLess node);
    void CaseTGreater(TGreater node);
    void CaseTLeftParentesis(TLeftParentesis node);
    void CaseTRightParentesis(TRightParentesis node);
    void CaseTComma(TComma node);
    void CaseTBlank(TBlank node);
    void CaseEOF(EOF node);
}


public class AnalysisAdapter : Analysis
{
    private Hashtable inhash;
    private Hashtable outhash;

    public virtual Object GetIn(Node node)
    {
        if(inhash == null)
        {
            return null;
        }

        return inhash[node];
    }

    public virtual void SetIn(Node node, Object inobj)
    {
        if(this.inhash == null)
        {
            this.inhash = new Hashtable(1);
        }

        if(inobj != null)
        {
            this.inhash[node] = inobj;
        }
        else
        {
            this.inhash.Remove(node);
        }
    }
    public virtual Object GetOut(Node node)
    {
        if(outhash == null)
        {
            return null;
        }

        return outhash[node];
    }

    public virtual void SetOut(Node node, Object outobj)
    {
        if(this.outhash == null)
        {
            this.outhash = new Hashtable(1);
        }

        if(outobj != null)
        {
            this.outhash[node] = outobj;
        }
        else
        {
            this.outhash.Remove(node);
        }
    }
    public virtual void CaseStart(Start node)
    {
        DefaultCase(node);
    }

    public virtual void CaseAProgramProgram(AProgramProgram node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAStatementCard(AStatementCard node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAReturnCard(AReturnCard node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAStopCard(AStopCard node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAExpressionCard(AExpressionCard node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAIfStatement(AIfStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAIfElseStatement(AIfElseStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAWhileStatement(AWhileStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseARepeatStatement(ARepeatStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseADamageStatement(ADamageStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAHealStatement(AHealStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAPullStatement(APullStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseARechargeStatement(ARechargeStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseARunStatement(ARunStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAInsertStatement(AInsertStatement node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAAddExpression(AAddExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseASubExpression(ASubExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAMulExpression(AMulExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseADivExpression(ADivExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAModExpression(AModExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseARandomExpression(ARandomExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseANumberExpression(ANumberExpression node)
    {
        DefaultCase(node);
    }
    public virtual void CaseAIdentifierExpression(AIdentifierExpression node)
    {
        DefaultCase(node);
    }

    public virtual void CaseTCollect(TCollect node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTIf(TIf node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTElse(TElse node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTWhile(TWhile node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTRepeat(TRepeat node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTStart(TStart node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTEnd(TEnd node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTReturn(TReturn node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTDamage(TDamage node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTHeal(THeal node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTPull(TPull node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTRecharge(TRecharge node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTRun(TRun node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTInsert(TInsert node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTStop(TStop node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTRandom(TRandom node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTIdentifier(TIdentifier node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTName(TName node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTNumber(TNumber node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTPlus(TPlus node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTMinus(TMinus node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTTimes(TTimes node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTDiv(TDiv node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTMod(TMod node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTLessOrEqual(TLessOrEqual node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTGreaterOrEqual(TGreaterOrEqual node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTEquals(TEquals node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTNotEquals(TNotEquals node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTNot(TNot node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTLess(TLess node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTGreater(TGreater node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTLeftParentesis(TLeftParentesis node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTRightParentesis(TRightParentesis node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTComma(TComma node)
    {
        DefaultCase(node);
    }
    public virtual void CaseTBlank(TBlank node)
    {
        DefaultCase(node);
    }

    public virtual void CaseEOF(EOF node)
    {
        DefaultCase(node);
    }

    public virtual void DefaultCase(Node node)
    {
    }
}


public class DepthFirstAdapter : AnalysisAdapter
{
    public virtual void InStart(Start node)
    {
        DefaultIn(node);
    }

    public virtual void OutStart(Start node)
    {
        DefaultOut(node);
    }

    public virtual void DefaultIn(Node node)
    {
    }

    public virtual void DefaultOut(Node node)
    {
    }

    public override void CaseStart(Start node)
    {
        InStart(node);
        node.GetPProgram().Apply(this);
        node.GetEOF().Apply(this);
        OutStart(node);
    }

    public virtual void InAProgramProgram(AProgramProgram node)
    {
        DefaultIn(node);
    }

    public virtual void OutAProgramProgram(AProgramProgram node)
    {
        DefaultOut(node);
    }

    public override void CaseAProgramProgram(AProgramProgram node)
    {
        InAProgramProgram(node);
        {
            Object[] temp = new Object[node.GetCard().Count];
            node.GetCard().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PCard) temp[i]).Apply(this);
            }
        }
        OutAProgramProgram(node);
    }
    public virtual void InAStatementCard(AStatementCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAStatementCard(AStatementCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAStatementCard(AStatementCard node)
    {
        InAStatementCard(node);
        {
            Object[] temp = new Object[node.GetIdentifier().Count];
            node.GetIdentifier().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((TIdentifier) temp[i]).Apply(this);
            }
        }
        {
            Object[] temp = new Object[node.GetStatement().Count];
            node.GetStatement().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        OutAStatementCard(node);
    }
    public virtual void InAReturnCard(AReturnCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAReturnCard(AReturnCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAReturnCard(AReturnCard node)
    {
        InAReturnCard(node);
        {
            Object[] temp = new Object[node.GetIdentifier().Count];
            node.GetIdentifier().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((TIdentifier) temp[i]).Apply(this);
            }
        }
        if(node.GetExpression() != null)
        {
            node.GetExpression().Apply(this);
        }
        OutAReturnCard(node);
    }
    public virtual void InAStopCard(AStopCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAStopCard(AStopCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAStopCard(AStopCard node)
    {
        InAStopCard(node);
        OutAStopCard(node);
    }
    public virtual void InAExpressionCard(AExpressionCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAExpressionCard(AExpressionCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAExpressionCard(AExpressionCard node)
    {
        InAExpressionCard(node);
        if(node.GetExpression() != null)
        {
            node.GetExpression().Apply(this);
        }
        OutAExpressionCard(node);
    }
    public virtual void InAIfStatement(AIfStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIfStatement(AIfStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAIfStatement(AIfStatement node)
    {
        InAIfStatement(node);
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        {
            Object[] temp = new Object[node.GetThen().Count];
            node.GetThen().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        OutAIfStatement(node);
    }
    public virtual void InAIfElseStatement(AIfElseStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIfElseStatement(AIfElseStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAIfElseStatement(AIfElseStatement node)
    {
        InAIfElseStatement(node);
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        {
            Object[] temp = new Object[node.GetThen().Count];
            node.GetThen().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        {
            Object[] temp = new Object[node.GetElse().Count];
            node.GetElse().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        OutAIfElseStatement(node);
    }
    public virtual void InAWhileStatement(AWhileStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAWhileStatement(AWhileStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAWhileStatement(AWhileStatement node)
    {
        InAWhileStatement(node);
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        {
            Object[] temp = new Object[node.GetDo().Count];
            node.GetDo().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        OutAWhileStatement(node);
    }
    public virtual void InARepeatStatement(ARepeatStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARepeatStatement(ARepeatStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARepeatStatement(ARepeatStatement node)
    {
        InARepeatStatement(node);
        if(node.GetTimes() != null)
        {
            node.GetTimes().Apply(this);
        }
        {
            Object[] temp = new Object[node.GetDo().Count];
            node.GetDo().CopyTo(temp, 0);
            for(int i = 0; i < temp.Length; i++)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        OutARepeatStatement(node);
    }
    public virtual void InADamageStatement(ADamageStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutADamageStatement(ADamageStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseADamageStatement(ADamageStatement node)
    {
        InADamageStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutADamageStatement(node);
    }
    public virtual void InAHealStatement(AHealStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAHealStatement(AHealStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAHealStatement(AHealStatement node)
    {
        InAHealStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutAHealStatement(node);
    }
    public virtual void InAPullStatement(APullStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAPullStatement(APullStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAPullStatement(APullStatement node)
    {
        InAPullStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutAPullStatement(node);
    }
    public virtual void InARechargeStatement(ARechargeStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARechargeStatement(ARechargeStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARechargeStatement(ARechargeStatement node)
    {
        InARechargeStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutARechargeStatement(node);
    }
    public virtual void InARunStatement(ARunStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARunStatement(ARunStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARunStatement(ARunStatement node)
    {
        InARunStatement(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutARunStatement(node);
    }
    public virtual void InAInsertStatement(AInsertStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAInsertStatement(AInsertStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAInsertStatement(AInsertStatement node)
    {
        InAInsertStatement(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutAInsertStatement(node);
    }
    public virtual void InAAddExpression(AAddExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAAddExpression(AAddExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAAddExpression(AAddExpression node)
    {
        InAAddExpression(node);
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        OutAAddExpression(node);
    }
    public virtual void InASubExpression(ASubExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutASubExpression(ASubExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseASubExpression(ASubExpression node)
    {
        InASubExpression(node);
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        OutASubExpression(node);
    }
    public virtual void InAMulExpression(AMulExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAMulExpression(AMulExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAMulExpression(AMulExpression node)
    {
        InAMulExpression(node);
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        OutAMulExpression(node);
    }
    public virtual void InADivExpression(ADivExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutADivExpression(ADivExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseADivExpression(ADivExpression node)
    {
        InADivExpression(node);
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        OutADivExpression(node);
    }
    public virtual void InAModExpression(AModExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAModExpression(AModExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAModExpression(AModExpression node)
    {
        InAModExpression(node);
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        OutAModExpression(node);
    }
    public virtual void InARandomExpression(ARandomExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutARandomExpression(ARandomExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseARandomExpression(ARandomExpression node)
    {
        InARandomExpression(node);
        if(node.GetMin() != null)
        {
            node.GetMin().Apply(this);
        }
        if(node.GetMax() != null)
        {
            node.GetMax().Apply(this);
        }
        OutARandomExpression(node);
    }
    public virtual void InANumberExpression(ANumberExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutANumberExpression(ANumberExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseANumberExpression(ANumberExpression node)
    {
        InANumberExpression(node);
        if(node.GetValue() != null)
        {
            node.GetValue().Apply(this);
        }
        OutANumberExpression(node);
    }
    public virtual void InAIdentifierExpression(AIdentifierExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIdentifierExpression(AIdentifierExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAIdentifierExpression(AIdentifierExpression node)
    {
        InAIdentifierExpression(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutAIdentifierExpression(node);
    }
}


public class ReversedDepthFirstAdapter : AnalysisAdapter
{
    public virtual void InStart(Start node)
    {
        DefaultIn(node);
    }

    public virtual void OutStart(Start node)
    {
        DefaultOut(node);
    }

    public virtual void DefaultIn(Node node)
    {
    }

    public virtual void DefaultOut(Node node)
    {
    }

    public override void CaseStart(Start node)
    {
        InStart(node);
        node.GetEOF().Apply(this);
        node.GetPProgram().Apply(this);
        OutStart(node);
    }

    public virtual void InAProgramProgram(AProgramProgram node)
    {
        DefaultIn(node);
    }

    public virtual void OutAProgramProgram(AProgramProgram node)
    {
        DefaultOut(node);
    }

    public override void CaseAProgramProgram(AProgramProgram node)
    {
        InAProgramProgram(node);
        {
            Object[] temp = new Object[node.GetCard().Count];
            node.GetCard().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PCard) temp[i]).Apply(this);
            }
        }
        OutAProgramProgram(node);
    }
    public virtual void InAStatementCard(AStatementCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAStatementCard(AStatementCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAStatementCard(AStatementCard node)
    {
        InAStatementCard(node);
        {
            Object[] temp = new Object[node.GetStatement().Count];
            node.GetStatement().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        {
            Object[] temp = new Object[node.GetIdentifier().Count];
            node.GetIdentifier().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((TIdentifier) temp[i]).Apply(this);
            }
        }
        OutAStatementCard(node);
    }
    public virtual void InAReturnCard(AReturnCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAReturnCard(AReturnCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAReturnCard(AReturnCard node)
    {
        InAReturnCard(node);
        if(node.GetExpression() != null)
        {
            node.GetExpression().Apply(this);
        }
        {
            Object[] temp = new Object[node.GetIdentifier().Count];
            node.GetIdentifier().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((TIdentifier) temp[i]).Apply(this);
            }
        }
        OutAReturnCard(node);
    }
    public virtual void InAStopCard(AStopCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAStopCard(AStopCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAStopCard(AStopCard node)
    {
        InAStopCard(node);
        OutAStopCard(node);
    }
    public virtual void InAExpressionCard(AExpressionCard node)
    {
        DefaultIn(node);
    }

    public virtual void OutAExpressionCard(AExpressionCard node)
    {
        DefaultOut(node);
    }

    public override void CaseAExpressionCard(AExpressionCard node)
    {
        InAExpressionCard(node);
        if(node.GetExpression() != null)
        {
            node.GetExpression().Apply(this);
        }
        OutAExpressionCard(node);
    }
    public virtual void InAIfStatement(AIfStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIfStatement(AIfStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAIfStatement(AIfStatement node)
    {
        InAIfStatement(node);
        {
            Object[] temp = new Object[node.GetThen().Count];
            node.GetThen().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        OutAIfStatement(node);
    }
    public virtual void InAIfElseStatement(AIfElseStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIfElseStatement(AIfElseStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAIfElseStatement(AIfElseStatement node)
    {
        InAIfElseStatement(node);
        {
            Object[] temp = new Object[node.GetElse().Count];
            node.GetElse().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        {
            Object[] temp = new Object[node.GetThen().Count];
            node.GetThen().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        OutAIfElseStatement(node);
    }
    public virtual void InAWhileStatement(AWhileStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAWhileStatement(AWhileStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAWhileStatement(AWhileStatement node)
    {
        InAWhileStatement(node);
        {
            Object[] temp = new Object[node.GetDo().Count];
            node.GetDo().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        if(node.GetCondition() != null)
        {
            node.GetCondition().Apply(this);
        }
        OutAWhileStatement(node);
    }
    public virtual void InARepeatStatement(ARepeatStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARepeatStatement(ARepeatStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARepeatStatement(ARepeatStatement node)
    {
        InARepeatStatement(node);
        {
            Object[] temp = new Object[node.GetDo().Count];
            node.GetDo().CopyTo(temp, 0);
            for(int i = temp.Length - 1; i >= 0; i--)
            {
                ((PStatement) temp[i]).Apply(this);
            }
        }
        if(node.GetTimes() != null)
        {
            node.GetTimes().Apply(this);
        }
        OutARepeatStatement(node);
    }
    public virtual void InADamageStatement(ADamageStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutADamageStatement(ADamageStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseADamageStatement(ADamageStatement node)
    {
        InADamageStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutADamageStatement(node);
    }
    public virtual void InAHealStatement(AHealStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAHealStatement(AHealStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAHealStatement(AHealStatement node)
    {
        InAHealStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutAHealStatement(node);
    }
    public virtual void InAPullStatement(APullStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAPullStatement(APullStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAPullStatement(APullStatement node)
    {
        InAPullStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutAPullStatement(node);
    }
    public virtual void InARechargeStatement(ARechargeStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARechargeStatement(ARechargeStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARechargeStatement(ARechargeStatement node)
    {
        InARechargeStatement(node);
        if(node.GetAmount() != null)
        {
            node.GetAmount().Apply(this);
        }
        OutARechargeStatement(node);
    }
    public virtual void InARunStatement(ARunStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutARunStatement(ARunStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseARunStatement(ARunStatement node)
    {
        InARunStatement(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutARunStatement(node);
    }
    public virtual void InAInsertStatement(AInsertStatement node)
    {
        DefaultIn(node);
    }

    public virtual void OutAInsertStatement(AInsertStatement node)
    {
        DefaultOut(node);
    }

    public override void CaseAInsertStatement(AInsertStatement node)
    {
        InAInsertStatement(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutAInsertStatement(node);
    }
    public virtual void InAAddExpression(AAddExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAAddExpression(AAddExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAAddExpression(AAddExpression node)
    {
        InAAddExpression(node);
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        OutAAddExpression(node);
    }
    public virtual void InASubExpression(ASubExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutASubExpression(ASubExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseASubExpression(ASubExpression node)
    {
        InASubExpression(node);
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        OutASubExpression(node);
    }
    public virtual void InAMulExpression(AMulExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAMulExpression(AMulExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAMulExpression(AMulExpression node)
    {
        InAMulExpression(node);
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        OutAMulExpression(node);
    }
    public virtual void InADivExpression(ADivExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutADivExpression(ADivExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseADivExpression(ADivExpression node)
    {
        InADivExpression(node);
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        OutADivExpression(node);
    }
    public virtual void InAModExpression(AModExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAModExpression(AModExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAModExpression(AModExpression node)
    {
        InAModExpression(node);
        if(node.GetRight() != null)
        {
            node.GetRight().Apply(this);
        }
        if(node.GetLeft() != null)
        {
            node.GetLeft().Apply(this);
        }
        OutAModExpression(node);
    }
    public virtual void InARandomExpression(ARandomExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutARandomExpression(ARandomExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseARandomExpression(ARandomExpression node)
    {
        InARandomExpression(node);
        if(node.GetMax() != null)
        {
            node.GetMax().Apply(this);
        }
        if(node.GetMin() != null)
        {
            node.GetMin().Apply(this);
        }
        OutARandomExpression(node);
    }
    public virtual void InANumberExpression(ANumberExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutANumberExpression(ANumberExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseANumberExpression(ANumberExpression node)
    {
        InANumberExpression(node);
        if(node.GetValue() != null)
        {
            node.GetValue().Apply(this);
        }
        OutANumberExpression(node);
    }
    public virtual void InAIdentifierExpression(AIdentifierExpression node)
    {
        DefaultIn(node);
    }

    public virtual void OutAIdentifierExpression(AIdentifierExpression node)
    {
        DefaultOut(node);
    }

    public override void CaseAIdentifierExpression(AIdentifierExpression node)
    {
        InAIdentifierExpression(node);
        if(node.GetName() != null)
        {
            node.GetName().Apply(this);
        }
        OutAIdentifierExpression(node);
    }
}
} // namespace CardLang.analysis
