/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using CardLang.node;

namespace CardLang.lexer {

internal class PushbackReader {
  private TextReader reader;
  private Stack stack = new Stack ();


  internal PushbackReader (TextReader reader)
  {
    this.reader = reader;
  }

  internal int Peek ()
  {
    if ( stack.Count > 0 ) return (int)stack.Peek();
    return reader.Peek();
  }

  internal int Read ()
  {
    if ( stack.Count > 0 ) return (int)stack.Pop();
    return reader.Read();
  }

  internal void Unread (int v)
  {
    stack.Push (v);
  }
}

public class LexerException : ApplicationException
{
    public LexerException(String message) : base (message)
    {
    }
}

public class Lexer
{
    protected Token token;
    protected State currentState = State.INITIAL;

    private PushbackReader input;
    private int line;
    private int pos;
    private bool cr;
    private bool eof;
    private StringBuilder text = new StringBuilder();

    protected virtual void Filter()
    {
    }

    public Lexer(TextReader input)
    {
        this.input = new PushbackReader(input);
    }

    public virtual Token Peek()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        return token;
    }

    public virtual Token Next()
    {
        while(token == null)
        {
            token = GetToken();
            Filter();
        }

        Token result = token;
        token = null;
        return result;
    }

    protected virtual Token GetToken()
    {
        int dfa_state = 0;

        int start_pos = pos;
        int start_line = line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        int[][][] gotoTable = Lexer.gotoTable[currentState.id()];
        int[] accept = Lexer.accept[currentState.id()];
        text.Length = 0;

        while(true)
        {
            int c = GetChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(cr)
                    {
                        cr = false;
                    }
                    else
                    {
                        line++;
                        pos = 0;
                    }
                    break;
                case 13:
                    line++;
                    pos = 0;
                    cr = true;
                    break;
                default:
                    pos++;
                    cr = false;
                    break;
                };

                text.Append((char) c);
                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.Length - 1;

                    while(low <= high)
                    {
                        int middle = (low + high) / 2;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = text.Length;
                    accept_pos = pos;
                    accept_line = line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            Token token = New0(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            Token token = New1(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            Token token = New2(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            Token token = New3(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            Token token = New4(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            Token token = New5(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            Token token = New6(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            Token token = New7(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            Token token = New8(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            Token token = New9(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            Token token = New10(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            Token token = New11(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            Token token = New12(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            Token token = New13(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            Token token = New14(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            Token token = New15(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            Token token = New16(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            Token token = New17(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            Token token = New18(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            Token token = New19(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            Token token = New20(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            Token token = New21(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            Token token = New22(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            Token token = New23(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            Token token = New24(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            Token token = New25(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            Token token = New26(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            Token token = New27(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            Token token = New28(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            Token token = New29(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            Token token = New30(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            Token token = New31(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            Token token = New32(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            Token token = New33(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            Token token = New34(
                                GetText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            PushBack(accept_length);
                            pos = accept_pos;
                            line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(text.Length > 0)
                    {
                        throw new LexerException(
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + text);
                    }
                    else
                    {
                        EOF token = new EOF(
                            start_line + 1,
                            start_pos + 1);
                        return token;
                    }
                }
            }
        }
    }

    private Token New0(String text, int line, int pos) { return new TCollect(text, line, pos); }
    private Token New1(String text, int line, int pos) { return new TIf(text, line, pos); }
    private Token New2(String text, int line, int pos) { return new TElse(text, line, pos); }
    private Token New3(String text, int line, int pos) { return new TWhile(text, line, pos); }
    private Token New4(String text, int line, int pos) { return new TRepeat(text, line, pos); }
    private Token New5(String text, int line, int pos) { return new TStart(text, line, pos); }
    private Token New6(String text, int line, int pos) { return new TEnd(text, line, pos); }
    private Token New7(String text, int line, int pos) { return new TReturn(text, line, pos); }
    private Token New8(String text, int line, int pos) { return new TDamage(text, line, pos); }
    private Token New9(String text, int line, int pos) { return new THeal(text, line, pos); }
    private Token New10(String text, int line, int pos) { return new TPull(text, line, pos); }
    private Token New11(String text, int line, int pos) { return new TRecharge(text, line, pos); }
    private Token New12(String text, int line, int pos) { return new TRun(text, line, pos); }
    private Token New13(String text, int line, int pos) { return new TInsert(text, line, pos); }
    private Token New14(String text, int line, int pos) { return new TStop(text, line, pos); }
    private Token New15(String text, int line, int pos) { return new TRandom(text, line, pos); }
    private Token New16(String text, int line, int pos) { return new TIdentifier(text, line, pos); }
    private Token New17(String text, int line, int pos) { return new TName(text, line, pos); }
    private Token New18(String text, int line, int pos) { return new TNumber(text, line, pos); }
    private Token New19(String text, int line, int pos) { return new TPlus(text, line, pos); }
    private Token New20(String text, int line, int pos) { return new TMinus(text, line, pos); }
    private Token New21(String text, int line, int pos) { return new TTimes(text, line, pos); }
    private Token New22(String text, int line, int pos) { return new TDiv(text, line, pos); }
    private Token New23(String text, int line, int pos) { return new TMod(text, line, pos); }
    private Token New24(String text, int line, int pos) { return new TLessOrEqual(text, line, pos); }
    private Token New25(String text, int line, int pos) { return new TGreaterOrEqual(text, line, pos); }
    private Token New26(String text, int line, int pos) { return new TEquals(text, line, pos); }
    private Token New27(String text, int line, int pos) { return new TNotEquals(text, line, pos); }
    private Token New28(String text, int line, int pos) { return new TNot(text, line, pos); }
    private Token New29(String text, int line, int pos) { return new TLess(text, line, pos); }
    private Token New30(String text, int line, int pos) { return new TGreater(text, line, pos); }
    private Token New31(String text, int line, int pos) { return new TLeftParentesis(text, line, pos); }
    private Token New32(String text, int line, int pos) { return new TRightParentesis(text, line, pos); }
    private Token New33(String text, int line, int pos) { return new TComma(text, line, pos); }
    private Token New34(String text, int line, int pos) { return new TBlank(text, line, pos); }

    private int GetChar()
    {
        if(eof)
        {
            return -1;
        }

        int result = input.Read();

        if(result == -1)
        {
            eof = true;
        }

        return result;
    }

    private void PushBack(int acceptLength)
    {
        int length = text.Length;
        for(int i = length - 1; i >= acceptLength; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }
    }


    protected virtual void Unread(Token token)
    {
        String text = token.Text;
        int length = text.Length;

        for(int i = length - 1; i >= 0; i--)
        {
            eof = false;

            input.Unread(text[i]);
        }

        pos = token.Pos - 1;
        line = token.Line - 1;
    }

    private string GetText(int acceptLength)
    {
        StringBuilder s = new StringBuilder(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.Append(text[i]);
        }

        return s.ToString();
    }

    private static int[][][][] gotoTable = {
      new int[][][] {
        new int[][] {
          new int[] {32, 32, 1},
          new int[] {33, 33, 2},
          new int[] {37, 37, 3},
          new int[] {40, 40, 4},
          new int[] {41, 41, 5},
          new int[] {42, 42, 6},
          new int[] {43, 43, 7},
          new int[] {44, 44, 8},
          new int[] {45, 45, 9},
          new int[] {47, 47, 10},
          new int[] {60, 60, 11},
          new int[] {61, 61, 12},
          new int[] {62, 62, 13},
          new int[] {65, 66, 14},
          new int[] {67, 67, 15},
          new int[] {68, 68, 16},
          new int[] {69, 69, 17},
          new int[] {70, 71, 14},
          new int[] {72, 72, 18},
          new int[] {73, 73, 19},
          new int[] {74, 79, 14},
          new int[] {80, 80, 20},
          new int[] {81, 81, 14},
          new int[] {82, 82, 21},
          new int[] {83, 83, 22},
          new int[] {84, 86, 14},
          new int[] {87, 87, 23},
          new int[] {88, 90, 14},
          new int[] {91, 91, 24},
          new int[] {92, 92, 25},
          new int[] {97, 98, 26},
          new int[] {99, 99, 27},
          new int[] {100, 100, 28},
          new int[] {101, 101, 29},
          new int[] {102, 103, 26},
          new int[] {104, 104, 30},
          new int[] {105, 105, 31},
          new int[] {106, 111, 26},
          new int[] {112, 112, 32},
          new int[] {113, 113, 26},
          new int[] {114, 114, 33},
          new int[] {115, 115, 34},
          new int[] {116, 118, 26},
          new int[] {119, 119, 35},
          new int[] {120, 122, 26},
        },
        new int[][] {
          new int[] {32, 32, 1},
          new int[] {92, 92, 25},
        },
        new int[][] {
          new int[] {61, 61, 36},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {61, 61, 37},
          new int[] {65, 90, 38},
          new int[] {97, 122, 39},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {61, 61, 40},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 78, 42},
          new int[] {79, 79, 45},
          new int[] {80, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 110, 44},
          new int[] {111, 111, 46},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 47},
          new int[] {66, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 97, 48},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 75, 42},
          new int[] {76, 76, 49},
          new int[] {77, 77, 42},
          new int[] {78, 78, 50},
          new int[] {79, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 107, 44},
          new int[] {108, 108, 51},
          new int[] {109, 109, 44},
          new int[] {110, 110, 52},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 68, 42},
          new int[] {69, 69, 53},
          new int[] {70, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 100, 44},
          new int[] {101, 101, 54},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 69, 42},
          new int[] {70, 70, 55},
          new int[] {71, 77, 42},
          new int[] {78, 78, 56},
          new int[] {79, 95, -19},
          new int[] {97, 101, 44},
          new int[] {102, 102, 57},
          new int[] {103, 109, 44},
          new int[] {110, 110, 58},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 84, 42},
          new int[] {85, 85, 59},
          new int[] {86, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 116, 44},
          new int[] {117, 117, 60},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 61},
          new int[] {66, 68, 42},
          new int[] {69, 69, 62},
          new int[] {70, 84, 42},
          new int[] {85, 85, 63},
          new int[] {86, 95, -22},
          new int[] {97, 97, 64},
          new int[] {98, 100, 44},
          new int[] {101, 101, 65},
          new int[] {102, 116, 44},
          new int[] {117, 117, 66},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 83, 42},
          new int[] {84, 84, 67},
          new int[] {85, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 115, 44},
          new int[] {116, 116, 68},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 71, 42},
          new int[] {72, 72, 69},
          new int[] {73, 90, 42},
          new int[] {95, 95, 43},
          new int[] {97, 103, 44},
          new int[] {104, 104, 70},
          new int[] {105, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 71},
        },
        new int[][] {
          new int[] {110, 110, 72},
          new int[] {114, 114, 73},
          new int[] {116, 116, 74},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 110, 44},
          new int[] {111, 111, 75},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 76},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 107, 44},
          new int[] {108, 108, 77},
          new int[] {109, 109, 44},
          new int[] {110, 110, 78},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 100, 44},
          new int[] {101, 101, 79},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 101, 44},
          new int[] {102, 102, 80},
          new int[] {103, 109, 44},
          new int[] {110, 110, 81},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 116, 44},
          new int[] {117, 117, 82},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 83},
          new int[] {98, 100, 44},
          new int[] {101, 101, 84},
          new int[] {102, 116, 44},
          new int[] {117, 117, 85},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 115, 44},
          new int[] {116, 116, 86},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 103, 44},
          new int[] {104, 104, 87},
          new int[] {105, 122, 44},
        },
        new int[][] {
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 57, 88},
          new int[] {62, 62, 89},
          new int[] {65, 90, 90},
          new int[] {97, 122, 91},
        },
        new int[][] {
          new int[] {48, 122, -40},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 92},
          new int[] {77, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 93},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 76, 42},
          new int[] {77, 77, 94},
          new int[] {78, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 108, 44},
          new int[] {109, 109, 95},
          new int[] {110, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 82, 42},
          new int[] {83, 83, 96},
          new int[] {84, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 67, 42},
          new int[] {68, 68, 97},
          new int[] {69, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 114, 44},
          new int[] {115, 115, 98},
          new int[] {116, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 99, 44},
          new int[] {100, 100, 99},
          new int[] {101, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 100},
          new int[] {66, 95, -18},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 101},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 82, -51},
          new int[] {83, 83, 102},
          new int[] {84, 122, -51},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 114, -53},
          new int[] {115, 115, 103},
          new int[] {116, 122, 44},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 104},
          new int[] {77, 122, -47},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 105},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 77, 42},
          new int[] {78, 78, 106},
          new int[] {79, 95, -19},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 66, 42},
          new int[] {67, 67, 107},
          new int[] {68, 79, 42},
          new int[] {80, 80, 108},
          new int[] {81, 83, 42},
          new int[] {84, 84, 109},
          new int[] {85, 95, -24},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 77, -63},
          new int[] {78, 78, 110},
          new int[] {79, 122, -63},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 109, 44},
          new int[] {110, 110, 111},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 98, 44},
          new int[] {99, 99, 112},
          new int[] {100, 111, 44},
          new int[] {112, 112, 113},
          new int[] {113, 115, 44},
          new int[] {116, 116, 114},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 109, -66},
          new int[] {110, 110, 115},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 116},
          new int[] {66, 78, 42},
          new int[] {79, 79, 117},
          new int[] {80, 95, -17},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 118},
          new int[] {98, 110, 44},
          new int[] {111, 111, 119},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 72, 42},
          new int[] {73, 73, 120},
          new int[] {74, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 104, 44},
          new int[] {105, 105, 121},
          new int[] {106, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 71},
          new int[] {93, 93, 122},
        },
        new int[][] {
          new int[] {32, 92, -3},
        },
        new int[][] {
          new int[] {32, 92, -3},
        },
        new int[][] {
          new int[] {32, 92, -3},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 123},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 108, -50},
          new int[] {109, 109, 124},
          new int[] {110, 122, 44},
        },
        new int[][] {
          new int[] {48, 114, -53},
          new int[] {115, 115, 125},
          new int[] {116, 122, 44},
        },
        new int[][] {
          new int[] {48, 99, -54},
          new int[] {100, 100, 126},
          new int[] {101, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 127},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 114, -53},
          new int[] {115, 115, 128},
          new int[] {116, 122, 44},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 129},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 109, -66},
          new int[] {110, 110, 130},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 98, -67},
          new int[] {99, 99, 131},
          new int[] {100, 111, 44},
          new int[] {112, 112, 132},
          new int[] {113, 115, 44},
          new int[] {116, 116, 133},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 109, -66},
          new int[] {110, 110, 134},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 135},
          new int[] {98, 110, 44},
          new int[] {111, 111, 136},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 104, -72},
          new int[] {105, 105, 137},
          new int[] {106, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -40},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 122, -40},
        },
        new int[][] {
          new int[] {48, 122, -40},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 138},
          new int[] {77, 122, -47},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 139},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 140},
          new int[] {66, 122, -55},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 141},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 142},
          new int[] {70, 95, -20},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 143},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 144},
          new int[] {77, 122, -47},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 145},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 146},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 147},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 148},
          new int[] {77, 122, -47},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 149},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 67, -52},
          new int[] {68, 68, 150},
          new int[] {69, 122, -52},
        },
        new int[][] {
          new int[] {48, 71, -25},
          new int[] {72, 72, 151},
          new int[] {73, 95, -25},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 152},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 84, -22},
          new int[] {85, 85, 153},
          new int[] {86, 95, -22},
          new int[] {97, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 99, -54},
          new int[] {100, 100, 154},
          new int[] {101, 122, 44},
        },
        new int[][] {
          new int[] {48, 103, -37},
          new int[] {104, 104, 155},
          new int[] {105, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 156},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 157},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 81, 42},
          new int[] {82, 82, 158},
          new int[] {83, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 79, 42},
          new int[] {80, 80, 159},
          new int[] {81, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 113, 44},
          new int[] {114, 114, 160},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 111, 44},
          new int[] {112, 112, 161},
          new int[] {113, 122, 44},
        },
        new int[][] {
          new int[] {48, 75, -19},
          new int[] {76, 76, 162},
          new int[] {77, 122, -47},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 163},
          new int[] {109, 122, 44},
        },
        new int[][] {
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 164},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 165},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 166},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 167},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 168},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 169},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 99, -54},
          new int[] {100, 100, 170},
          new int[] {101, 122, 44},
        },
        new int[][] {
          new int[] {48, 103, -37},
          new int[] {104, 104, 171},
          new int[] {105, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 172},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 116, -34},
          new int[] {117, 117, 173},
          new int[] {118, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 174},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 111, -121},
          new int[] {112, 112, 175},
          new int[] {113, 122, 44},
        },
        new int[][] {
          new int[] {48, 107, -31},
          new int[] {108, 108, 176},
          new int[] {109, 122, 44},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 177},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 178},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 70, 42},
          new int[] {71, 71, 179},
          new int[] {72, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 102, 44},
          new int[] {103, 103, 180},
          new int[] {104, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 81, -118},
          new int[] {82, 82, 181},
          new int[] {83, 122, -118},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 182},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 78, -17},
          new int[] {79, 79, 183},
          new int[] {80, 122, -69},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 184},
          new int[] {66, 122, -55},
        },
        new int[][] {
          new int[] {48, 57, 41},
          new int[] {65, 65, 185},
          new int[] {66, 122, -55},
        },
        new int[][] {
          new int[] {48, 81, -118},
          new int[] {82, 82, 186},
          new int[] {83, 122, -118},
        },
        new int[][] {
          new int[] {48, 110, -29},
          new int[] {111, 111, 187},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 188},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 189},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 190},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 83, -24},
          new int[] {84, 84, 191},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 192},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 193},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 194},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 195},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 102, -143},
          new int[] {103, 103, 196},
          new int[] {104, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 197},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 110, -29},
          new int[] {111, 111, 198},
          new int[] {112, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 199},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 95, -16},
          new int[] {97, 97, 200},
          new int[] {98, 122, 44},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 201},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 202},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 203},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 66, -64},
          new int[] {67, 67, 204},
          new int[] {68, 90, 42},
          new int[] {95, 122, -16},
        },
        new int[][] {
          new int[] {48, 98, -67},
          new int[] {99, 99, 205},
          new int[] {100, 122, 44},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 206},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 207},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 83, -24},
          new int[] {84, 84, 208},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 209},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 76, -49},
          new int[] {77, 77, 210},
          new int[] {78, 122, -49},
        },
        new int[][] {
          new int[] {48, 81, -118},
          new int[] {82, 82, 211},
          new int[] {83, 122, -118},
        },
        new int[][] {
          new int[] {48, 83, -24},
          new int[] {84, 84, 212},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {48, 77, -63},
          new int[] {78, 78, 213},
          new int[] {79, 122, -63},
        },
        new int[][] {
          new int[] {48, 108, -50},
          new int[] {109, 109, 214},
          new int[] {110, 122, 44},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 215},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 216},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 109, -66},
          new int[] {110, 110, 217},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 98, -67},
          new int[] {99, 99, 218},
          new int[] {100, 122, 44},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 219},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 220},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 108, -50},
          new int[] {109, 109, 221},
          new int[] {110, 122, 44},
        },
        new int[][] {
          new int[] {48, 113, -120},
          new int[] {114, 114, 222},
          new int[] {115, 122, 44},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 223},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 109, -66},
          new int[] {110, 110, 224},
          new int[] {111, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 83, -24},
          new int[] {84, 84, 225},
          new int[] {85, 122, -64},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 226},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 70, -142},
          new int[] {71, 71, 227},
          new int[] {72, 122, -142},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 102, -143},
          new int[] {103, 103, 228},
          new int[] {104, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 115, -36},
          new int[] {116, 116, 229},
          new int[] {117, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 102, -143},
          new int[] {103, 103, 230},
          new int[] {104, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 68, -20},
          new int[] {69, 69, 231},
          new int[] {70, 122, -98},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 232},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 100, -32},
          new int[] {101, 101, 233},
          new int[] {102, 122, 44},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
        new int[][] {
          new int[] {48, 122, -16},
        },
      },
    };

    private static int[][] accept = {
      new int[] {
        -1, 34, 28, 23, 31, 32, 21, 19, 33, 20, 22, 29, 26, 30, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 17, -1, -1, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 27, 24, -1, -1, 25, 17, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, 1, 17, 1, 17, 17, 17, 17, 17, 17, 
        17, 17, 17, 17, 17, 17, 17, -1, 34, 34, 34, 17, 17, 17, 17, 17, 
        1, 17, 17, 17, 17, 17, 17, 17, -1, 16, -1, -1, 17, 17, 17, 17, 
        17, 6, 17, 6, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 12, 17, 
        17, 17, 17, 12, 17, 17, 17, 17, 17, 17, 18, 17, 17, 17, 6, 17, 
        17, 17, 17, 17, 17, 17, 12, 17, 17, 17, 17, 17, 17, 17, 2, 2, 
        9, 9, 17, 17, 10, 10, 17, 17, 17, 17, 17, 17, 17, 17, 17, 14, 
        17, 14, 17, 17, 17, 17, 2, 9, 17, 10, 17, 17, 17, 17, 17, 14, 
        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 5, 
        5, 3, 3, 17, 17, 17, 17, 17, 17, 17, 5, 3, 17, 17, 8, 8, 
        13, 13, 15, 17, 4, 7, 15, 17, 4, 7, 17, 8, 13, 15, 17, 4, 
        7, 0, 0, 17, 17, 0, 17, 11, 11, 11, 
      },
    };

    public class State
    {
        public static State INITIAL = new State(0);

        private int _id;

        private State(int _id)
        {
            this._id = _id;
        }

        public int id()
        {
            return _id;
        }
    }
}
}
