/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;
using System.IO;
using CardLang.node;
using CardLang.lexer;
using CardLang.analysis;

namespace CardLang.parser {

public class ParserException : ApplicationException
{
    Token token;

    public ParserException(Token token, String  message) : base(message)
    {
        this.token = token;
    }

    public Token Token
    {
      get { return token; }
    }
}

internal class State
{
    internal int state;
    internal ArrayList nodes;

    internal State(int state, ArrayList nodes)
    {
        this.state = state;
        this.nodes = nodes;
    }
}

internal class TokenIndex : AnalysisAdapter
{
    internal int index;

    public override void CaseTCollect(TCollect node)
    {
        index = 0;
    }

    public override void CaseTIf(TIf node)
    {
        index = 1;
    }

    public override void CaseTElse(TElse node)
    {
        index = 2;
    }

    public override void CaseTWhile(TWhile node)
    {
        index = 3;
    }

    public override void CaseTRepeat(TRepeat node)
    {
        index = 4;
    }

    public override void CaseTStart(TStart node)
    {
        index = 5;
    }

    public override void CaseTEnd(TEnd node)
    {
        index = 6;
    }

    public override void CaseTReturn(TReturn node)
    {
        index = 7;
    }

    public override void CaseTDamage(TDamage node)
    {
        index = 8;
    }

    public override void CaseTHeal(THeal node)
    {
        index = 9;
    }

    public override void CaseTPull(TPull node)
    {
        index = 10;
    }

    public override void CaseTRecharge(TRecharge node)
    {
        index = 11;
    }

    public override void CaseTRun(TRun node)
    {
        index = 12;
    }

    public override void CaseTInsert(TInsert node)
    {
        index = 13;
    }

    public override void CaseTStop(TStop node)
    {
        index = 14;
    }

    public override void CaseTRandom(TRandom node)
    {
        index = 15;
    }

    public override void CaseTIdentifier(TIdentifier node)
    {
        index = 16;
    }

    public override void CaseTName(TName node)
    {
        index = 17;
    }

    public override void CaseTNumber(TNumber node)
    {
        index = 18;
    }

    public override void CaseTPlus(TPlus node)
    {
        index = 19;
    }

    public override void CaseTMinus(TMinus node)
    {
        index = 20;
    }

    public override void CaseTTimes(TTimes node)
    {
        index = 21;
    }

    public override void CaseTDiv(TDiv node)
    {
        index = 22;
    }

    public override void CaseTMod(TMod node)
    {
        index = 23;
    }

    public override void CaseTLessOrEqual(TLessOrEqual node)
    {
        index = 24;
    }

    public override void CaseTGreaterOrEqual(TGreaterOrEqual node)
    {
        index = 25;
    }

    public override void CaseTEquals(TEquals node)
    {
        index = 26;
    }

    public override void CaseTNotEquals(TNotEquals node)
    {
        index = 27;
    }

    public override void CaseTNot(TNot node)
    {
        index = 28;
    }

    public override void CaseTLess(TLess node)
    {
        index = 29;
    }

    public override void CaseTGreater(TGreater node)
    {
        index = 30;
    }

    public override void CaseTLeftParentesis(TLeftParentesis node)
    {
        index = 31;
    }

    public override void CaseTRightParentesis(TRightParentesis node)
    {
        index = 32;
    }

    public override void CaseTComma(TComma node)
    {
        index = 33;
    }

    public override void CaseEOF(EOF node)
    {
        index = 34;
    }
}

public class Parser
{
    private Analysis ignoredTokens = new AnalysisAdapter();
    public Analysis IgnoredTokens
    {
      get { return ignoredTokens; }
    }

    protected ArrayList nodeList;

    private Lexer lexer;
    private Stack stack = new Stack();
    private int last_shift;
    private int last_pos;
    private int last_line;
    private Token last_token;
    private TokenIndex converter = new TokenIndex();
    private int[] action = new int[2];

    private const int SHIFT = 0;
    private const int REDUCE = 1;
    private const int ACCEPT = 2;
    private const int ERROR = 3;

    public Parser(Lexer lexer)
    {
        this.lexer = lexer;
    }

    private int GoTo(int index)
    {
        int state = State();
        int low = 1;
        int high = gotoTable[index].Length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private void Push(int numstate, ArrayList listNode)
    {
        this.nodeList = listNode;

        stack.Push(new State(numstate, this.nodeList));
    }

    private int State()
    {
        State s = (State) stack.Peek();
        return s.state;
    }

    private ArrayList Pop()
    {
        return (ArrayList) ((State) stack.Pop()).nodes;
    }

    private int Index(Switchable token)
    {
        converter.index = -1;
        token.Apply(converter);
        return converter.index;
    }

    public Start Parse()
    {
        Push(0, null);

        IList ign = null;
        while(true)
        {
            while(Index(lexer.Peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new TypedList(NodeCast.Instance);
                }

                ign.Add(lexer.Next());
            }

            if(ign != null)
            {
                ignoredTokens.SetIn(lexer.Peek(), ign);
                ign = null;
            }

            last_pos = lexer.Peek().Pos;
            last_line = lexer.Peek().Line;
            last_token = lexer.Peek();

            int index = Index(lexer.Peek());
            action[0] = actionTable[State()][0][1];
            action[1] = actionTable[State()][0][2];

            int low = 1;
            int high = actionTable[State()].Length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < actionTable[State()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > actionTable[State()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    action[0] = actionTable[State()][middle][1];
                    action[1] = actionTable[State()][middle][2];
                    break;
                }
            }

            switch(action[0])
            {
                case SHIFT:
        {
            ArrayList list = new ArrayList();
            list.Add(lexer.Next());
                        Push(action[1], list);
                        last_shift = action[1];
                    }
        break;
                case REDUCE:
                    switch(action[1])
                    {
                    case 0:
        {
      ArrayList list = New0();
      Push(GoTo(0), list);
        }
        break;
                    case 1:
        {
      ArrayList list = New1();
      Push(GoTo(0), list);
        }
        break;
                    case 2:
        {
      ArrayList list = New2();
      Push(GoTo(1), list);
        }
        break;
                    case 3:
        {
      ArrayList list = New3();
      Push(GoTo(1), list);
        }
        break;
                    case 4:
        {
      ArrayList list = New4();
      Push(GoTo(1), list);
        }
        break;
                    case 5:
        {
      ArrayList list = New5();
      Push(GoTo(1), list);
        }
        break;
                    case 6:
        {
      ArrayList list = New6();
      Push(GoTo(1), list);
        }
        break;
                    case 7:
        {
      ArrayList list = New7();
      Push(GoTo(1), list);
        }
        break;
                    case 8:
        {
      ArrayList list = New8();
      Push(GoTo(2), list);
        }
        break;
                    case 9:
        {
      ArrayList list = New9();
      Push(GoTo(2), list);
        }
        break;
                    case 10:
        {
      ArrayList list = New10();
      Push(GoTo(3), list);
        }
        break;
                    case 11:
        {
      ArrayList list = New11();
      Push(GoTo(3), list);
        }
        break;
                    case 12:
        {
      ArrayList list = New12();
      Push(GoTo(3), list);
        }
        break;
                    case 13:
        {
      ArrayList list = New13();
      Push(GoTo(3), list);
        }
        break;
                    case 14:
        {
      ArrayList list = New14();
      Push(GoTo(3), list);
        }
        break;
                    case 15:
        {
      ArrayList list = New15();
      Push(GoTo(3), list);
        }
        break;
                    case 16:
        {
      ArrayList list = New16();
      Push(GoTo(3), list);
        }
        break;
                    case 17:
        {
      ArrayList list = New17();
      Push(GoTo(3), list);
        }
        break;
                    case 18:
        {
      ArrayList list = New18();
      Push(GoTo(3), list);
        }
        break;
                    case 19:
        {
      ArrayList list = New19();
      Push(GoTo(3), list);
        }
        break;
                    case 20:
        {
      ArrayList list = New20();
      Push(GoTo(4), list);
        }
        break;
                    case 21:
        {
      ArrayList list = New21();
      Push(GoTo(4), list);
        }
        break;
                    case 22:
        {
      ArrayList list = New22();
      Push(GoTo(4), list);
        }
        break;
                    case 23:
        {
      ArrayList list = New23();
      Push(GoTo(5), list);
        }
        break;
                    case 24:
        {
      ArrayList list = New24();
      Push(GoTo(5), list);
        }
        break;
                    case 25:
        {
      ArrayList list = New25();
      Push(GoTo(5), list);
        }
        break;
                    case 26:
        {
      ArrayList list = New26();
      Push(GoTo(5), list);
        }
        break;
                    case 27:
        {
      ArrayList list = New27();
      Push(GoTo(6), list);
        }
        break;
                    case 28:
        {
      ArrayList list = New28();
      Push(GoTo(6), list);
        }
        break;
                    case 29:
        {
      ArrayList list = New29();
      Push(GoTo(6), list);
        }
        break;
                    case 30:
        {
      ArrayList list = New30();
      Push(GoTo(6), list);
        }
        break;
                    case 31:
        {
      ArrayList list = New31();
      Push(GoTo(7), list);
        }
        break;
                    case 32:
        {
      ArrayList list = New32();
      Push(GoTo(7), list);
        }
        break;
                    case 33:
        {
      ArrayList list = New33();
      Push(GoTo(8), list);
        }
        break;
                    case 34:
        {
      ArrayList list = New34();
      Push(GoTo(8), list);
        }
        break;
                    case 35:
        {
      ArrayList list = New35();
      Push(GoTo(9), list);
        }
        break;
                    case 36:
        {
      ArrayList list = New36();
      Push(GoTo(9), list);
        }
        break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) lexer.Next();
                        PProgram node1 = (PProgram) ((ArrayList)Pop())[0];
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(last_token,
                        "[" + last_line + "," + last_pos + "] " +
                        errorMessages[errors[action[1]]]);
            }
        }
    }

    ArrayList New0()
    {
        ArrayList nodeList = new ArrayList();
        TypedList listNode2 = new TypedList();
        AProgramProgram pprogramNode1 = new AProgramProgram (
              listNode2
        );
        nodeList.Add(pprogramNode1);
        return nodeList;
    }
    ArrayList New1()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode2 = (TypedList)nodeArrayList1[0];
        if ( listNode2 != null )
        {
            listNode3.AddAll(listNode2);
        }
        AProgramProgram pprogramNode1 = new AProgramProgram (
              listNode3
        );
        nodeList.Add(pprogramNode1);
        return nodeList;
    }
    ArrayList New2()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        TypedList listNode4 = new TypedList();
        TypedList listNode3 = (TypedList)nodeArrayList2[0];
        if ( listNode3 != null )
        {
            listNode4.AddAll(listNode3);
        }
        AStatementCard pcardNode1 = new AStatementCard (
              listNode2,
              listNode4
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New3()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode5 = new TypedList();
        TypedList listNode2 = (TypedList)nodeArrayList2[0];
        if ( listNode2 != null )
        {
            listNode3.AddAll(listNode2);
        }
        TypedList listNode4 = (TypedList)nodeArrayList3[0];
        if ( listNode4 != null )
        {
            listNode5.AddAll(listNode4);
        }
        AStatementCard pcardNode1 = new AStatementCard (
              listNode3,
              listNode5
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New4()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList4 = (ArrayList) Pop();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        AReturnCard pcardNode1 = new AReturnCard (
              listNode2,
              pexpressionNode3
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New5()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList5 = (ArrayList) Pop();
        ArrayList nodeArrayList4 = (ArrayList) Pop();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode2 = (TypedList)nodeArrayList2[0];
        if ( listNode2 != null )
        {
            listNode3.AddAll(listNode2);
        }
        PExpression pexpressionNode4 = (PExpression)nodeArrayList4[0];
        AReturnCard pcardNode1 = new AReturnCard (
              listNode3,
              pexpressionNode4
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New6()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        AExpressionCard pcardNode1 = new AExpressionCard (
              pexpressionNode2
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New7()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        AStopCard pcardNode1 = new AStopCard (
        );
        nodeList.Add(pcardNode1);
        return nodeList;
    }
    ArrayList New8()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode1 = new TypedList();
        nodeList.Add(listNode1);
        return nodeList;
    }
    ArrayList New9()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        TypedList listNode1 = (TypedList)nodeArrayList2[0];
        if ( listNode1 != null )
        {
            listNode2.AddAll(listNode1);
        }
        nodeList.Add(listNode2);
        return nodeList;
    }
    ArrayList New10()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode4 = new TypedList();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        TypedList listNode3 = (TypedList)nodeArrayList3[0];
        if ( listNode3 != null )
        {
            listNode4.AddAll(listNode3);
        }
        AIfStatement pstatementNode1 = new AIfStatement (
              pexpressionNode2,
              listNode4
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New11()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList5 = (ArrayList) Pop();
        ArrayList nodeArrayList4 = (ArrayList) Pop();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode4 = new TypedList();
        TypedList listNode6 = new TypedList();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        TypedList listNode3 = (TypedList)nodeArrayList3[0];
        if ( listNode3 != null )
        {
            listNode4.AddAll(listNode3);
        }
        TypedList listNode5 = (TypedList)nodeArrayList5[0];
        if ( listNode5 != null )
        {
            listNode6.AddAll(listNode5);
        }
        AIfElseStatement pstatementNode1 = new AIfElseStatement (
              pexpressionNode2,
              listNode4,
              listNode6
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New12()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode4 = new TypedList();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        TypedList listNode3 = (TypedList)nodeArrayList3[0];
        if ( listNode3 != null )
        {
            listNode4.AddAll(listNode3);
        }
        AWhileStatement pstatementNode1 = new AWhileStatement (
              pexpressionNode2,
              listNode4
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New13()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode4 = new TypedList();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        TypedList listNode3 = (TypedList)nodeArrayList3[0];
        if ( listNode3 != null )
        {
            listNode4.AddAll(listNode3);
        }
        ARepeatStatement pstatementNode1 = new ARepeatStatement (
              pexpressionNode2,
              listNode4
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New14()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        ADamageStatement pstatementNode1 = new ADamageStatement (
              pexpressionNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New15()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        AHealStatement pstatementNode1 = new AHealStatement (
              pexpressionNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New16()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        APullStatement pstatementNode1 = new APullStatement (
              pexpressionNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New17()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        ARechargeStatement pstatementNode1 = new ARechargeStatement (
              pexpressionNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New18()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TName tnameNode2 = (TName)nodeArrayList2[0];
        ARunStatement pstatementNode1 = new ARunStatement (
              tnameNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New19()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TIdentifier tidentifierNode2 = (TIdentifier)nodeArrayList2[0];
        AInsertStatement pstatementNode1 = new AInsertStatement (
              tidentifierNode2
        );
        nodeList.Add(pstatementNode1);
        return nodeList;
    }
    ArrayList New20()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        AAddExpression pexpressionNode1 = new AAddExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New21()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        ASubExpression pexpressionNode1 = new ASubExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New22()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode1 = (PExpression)nodeArrayList1[0];
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New23()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        AMulExpression pexpressionNode1 = new AMulExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New24()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        ADivExpression pexpressionNode1 = new ADivExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New25()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList1[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        AModExpression pexpressionNode1 = new AModExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New26()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode1 = (PExpression)nodeArrayList1[0];
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New27()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TNumber tnumberNode2 = (TNumber)nodeArrayList1[0];
        ANumberExpression pexpressionNode1 = new ANumberExpression (
              tnumberNode2
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New28()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TIdentifier tidentifierNode2 = (TIdentifier)nodeArrayList1[0];
        AIdentifierExpression pexpressionNode1 = new AIdentifierExpression (
              tidentifierNode2
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New29()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode2 = (PExpression)nodeArrayList2[0];
        PExpression pexpressionNode3 = (PExpression)nodeArrayList3[0];
        ARandomExpression pexpressionNode1 = new ARandomExpression (
              pexpressionNode2,
              pexpressionNode3
        );
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New30()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList3 = (ArrayList) Pop();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        PExpression pexpressionNode1 = (PExpression)nodeArrayList2[0];
        nodeList.Add(pexpressionNode1);
        return nodeList;
    }
    ArrayList New31()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        PCard pcardNode1 = (PCard)nodeArrayList1[0];
        if ( pcardNode1 != null )
        {
            listNode2.Add(pcardNode1);
        }
        nodeList.Add(listNode2);
        return nodeList;
    }
    ArrayList New32()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode1 = (TypedList)nodeArrayList1[0];
        PCard pcardNode2 = (PCard)nodeArrayList2[0];
        if ( listNode1 != null )
        {
            listNode3.AddAll(listNode1);
        }
        if ( pcardNode2 != null )
        {
            listNode3.Add(pcardNode2);
        }
        nodeList.Add(listNode3);
        return nodeList;
    }
    ArrayList New33()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        TIdentifier tidentifierNode1 = (TIdentifier)nodeArrayList1[0];
        if ( tidentifierNode1 != null )
        {
            listNode2.Add(tidentifierNode1);
        }
        nodeList.Add(listNode2);
        return nodeList;
    }
    ArrayList New34()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode1 = (TypedList)nodeArrayList1[0];
        TIdentifier tidentifierNode2 = (TIdentifier)nodeArrayList2[0];
        if ( listNode1 != null )
        {
            listNode3.AddAll(listNode1);
        }
        if ( tidentifierNode2 != null )
        {
            listNode3.Add(tidentifierNode2);
        }
        nodeList.Add(listNode3);
        return nodeList;
    }
    ArrayList New35()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode2 = new TypedList();
        PStatement pstatementNode1 = (PStatement)nodeArrayList1[0];
        if ( pstatementNode1 != null )
        {
            listNode2.Add(pstatementNode1);
        }
        nodeList.Add(listNode2);
        return nodeList;
    }
    ArrayList New36()
    {
        ArrayList nodeList = new ArrayList();
        ArrayList nodeArrayList2 = (ArrayList) Pop();
        ArrayList nodeArrayList1 = (ArrayList) Pop();
        TypedList listNode3 = new TypedList();
        TypedList listNode1 = (TypedList)nodeArrayList1[0];
        PStatement pstatementNode2 = (PStatement)nodeArrayList2[0];
        if ( listNode1 != null )
        {
            listNode3.AddAll(listNode1);
        }
        if ( pstatementNode2 != null )
        {
            listNode3.Add(pstatementNode2);
        }
        nodeList.Add(listNode3);
        return nodeList;
    }

    private static int[][][] actionTable = {
      new int[][] {
        new int[] {-1, 1, 0},
        new int[] {0, 0, 1},
        new int[] {14, 0, 2},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 1},
        new int[] {5, 0, 13},
        new int[] {7, 0, 14},
        new int[] {16, 0, 15},
      },
      new int[][] {
        new int[] {-1, 1, 7},
      },
      new int[][] {
        new int[] {-1, 3, 3},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 28},
      },
      new int[][] {
        new int[] {-1, 1, 27},
      },
      new int[][] {
        new int[] {-1, 3, 6},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 7},
        new int[] {34, 2, -1},
      },
      new int[][] {
        new int[] {-1, 1, 31},
      },
      new int[][] {
        new int[] {-1, 1, 6},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 22},
        new int[] {21, 0, 22},
        new int[] {22, 0, 23},
        new int[] {23, 0, 24},
      },
      new int[][] {
        new int[] {-1, 1, 26},
      },
      new int[][] {
        new int[] {-1, 1, 1},
        new int[] {0, 0, 1},
        new int[] {14, 0, 2},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 13},
        new int[] {1, 0, 26},
        new int[] {3, 0, 27},
        new int[] {4, 0, 28},
        new int[] {6, 0, 29},
        new int[] {8, 0, 30},
        new int[] {9, 0, 31},
        new int[] {10, 0, 32},
        new int[] {11, 0, 33},
        new int[] {12, 0, 34},
        new int[] {13, 0, 35},
      },
      new int[][] {
        new int[] {-1, 3, 14},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 33},
      },
      new int[][] {
        new int[] {-1, 1, 2},
      },
      new int[][] {
        new int[] {-1, 3, 17},
        new int[] {5, 0, 13},
        new int[] {7, 0, 39},
        new int[] {16, 0, 40},
      },
      new int[][] {
        new int[] {-1, 3, 18},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 19},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
        new int[] {32, 0, 43},
      },
      new int[][] {
        new int[] {-1, 3, 20},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 21},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 22},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 23},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 24},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 32},
      },
      new int[][] {
        new int[] {-1, 3, 26},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 27},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 28},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 8},
      },
      new int[][] {
        new int[] {-1, 3, 30},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 31},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 32},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 33},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 3, 34},
        new int[] {17, 0, 56},
      },
      new int[][] {
        new int[] {-1, 3, 35},
        new int[] {16, 0, 57},
      },
      new int[][] {
        new int[] {-1, 1, 35},
      },
      new int[][] {
        new int[] {-1, 3, 37},
        new int[] {1, 0, 26},
        new int[] {3, 0, 27},
        new int[] {4, 0, 28},
        new int[] {6, 0, 58},
        new int[] {8, 0, 30},
        new int[] {9, 0, 31},
        new int[] {10, 0, 32},
        new int[] {11, 0, 33},
        new int[] {12, 0, 34},
        new int[] {13, 0, 35},
      },
      new int[][] {
        new int[] {-1, 3, 38},
        new int[] {6, 0, 60},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 3, 39},
        new int[] {15, 0, 3},
        new int[] {16, 0, 4},
        new int[] {18, 0, 5},
        new int[] {31, 0, 6},
      },
      new int[][] {
        new int[] {-1, 1, 34},
      },
      new int[][] {
        new int[] {-1, 1, 3},
      },
      new int[][] {
        new int[] {-1, 1, 29},
      },
      new int[][] {
        new int[] {-1, 1, 30},
      },
      new int[][] {
        new int[] {-1, 1, 20},
        new int[] {21, 0, 22},
        new int[] {22, 0, 23},
        new int[] {23, 0, 24},
      },
      new int[][] {
        new int[] {-1, 1, 21},
        new int[] {21, 0, 22},
        new int[] {22, 0, 23},
        new int[] {23, 0, 24},
      },
      new int[][] {
        new int[] {-1, 1, 23},
      },
      new int[][] {
        new int[] {-1, 1, 24},
      },
      new int[][] {
        new int[] {-1, 1, 25},
      },
      new int[][] {
        new int[] {-1, 3, 49},
        new int[] {5, 0, 13},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 3, 50},
        new int[] {5, 0, 13},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 3, 51},
        new int[] {5, 0, 13},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 14},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 15},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 16},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 17},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 18},
      },
      new int[][] {
        new int[] {-1, 1, 19},
      },
      new int[][] {
        new int[] {-1, 1, 9},
      },
      new int[][] {
        new int[] {-1, 1, 36},
      },
      new int[][] {
        new int[] {-1, 1, 4},
      },
      new int[][] {
        new int[] {-1, 3, 61},
        new int[] {6, 0, 65},
        new int[] {19, 0, 20},
        new int[] {20, 0, 21},
      },
      new int[][] {
        new int[] {-1, 1, 10},
        new int[] {2, 0, 66},
      },
      new int[][] {
        new int[] {-1, 1, 12},
      },
      new int[][] {
        new int[] {-1, 1, 13},
      },
      new int[][] {
        new int[] {-1, 1, 5},
      },
      new int[][] {
        new int[] {-1, 3, 66},
        new int[] {5, 0, 13},
      },
      new int[][] {
        new int[] {-1, 1, 11},
      },
    };

    private static int[][][] gotoTable  = {
      new int[][] {
        new int[] {-1, 7},
      },
      new int[][] {
        new int[] {-1, 8},
        new int[] {12, 25},
      },
      new int[][] {
        new int[] {-1, 16},
        new int[] {17, 41},
        new int[] {49, 62},
        new int[] {50, 63},
        new int[] {51, 64},
        new int[] {66, 67},
      },
      new int[][] {
        new int[] {-1, 36},
        new int[] {37, 59},
      },
      new int[][] {
        new int[] {-1, 9},
        new int[] {6, 19},
        new int[] {14, 38},
        new int[] {26, 49},
        new int[] {27, 50},
        new int[] {28, 51},
        new int[] {30, 52},
        new int[] {31, 53},
        new int[] {32, 54},
        new int[] {33, 55},
        new int[] {39, 61},
      },
      new int[][] {
        new int[] {-1, 10},
        new int[] {20, 44},
        new int[] {21, 45},
      },
      new int[][] {
        new int[] {-1, 11},
        new int[] {3, 18},
        new int[] {18, 42},
        new int[] {22, 46},
        new int[] {23, 47},
        new int[] {24, 48},
      },
      new int[][] {
        new int[] {-1, 12},
      },
      new int[][] {
        new int[] {-1, 17},
      },
      new int[][] {
        new int[] {-1, 37},
      },
    };

    private static String[] errorMessages = {
      "expecting: collect, stop, random, identifier, number, '(', EOF",
      "expecting: start, return, identifier",
      "expecting: random, identifier, number, '('",
      "expecting: collect, if, while, repeat, start, end, damage, heal, pull, recharge, run, insert, stop, random, identifier, number, '+', '-', '*', '/', '%', '(', ')', EOF",
      "expecting: EOF",
      "expecting: collect, stop, random, identifier, number, '+', '-', '(', EOF",
      "expecting: if, while, repeat, end, damage, heal, pull, recharge, run, insert",
      "expecting: '+', '-', ')'",
      "expecting: collect, if, else, while, repeat, end, damage, heal, pull, recharge, run, insert, stop, random, identifier, number, '(', EOF",
      "expecting: name",
      "expecting: identifier",
      "expecting: end, '+', '-'",
      "expecting: start, '+', '-'",
      "expecting: if, while, repeat, end, damage, heal, pull, recharge, run, insert, '+', '-'",
      "expecting: if, else, while, repeat, end, damage, heal, pull, recharge, run, insert",
      "expecting: start",
    };

    private static int[] errors = {
      0, 1, 0, 2, 3, 3, 2, 4, 0, 5, 3, 3, 0, 6, 2, 1, 
      0, 1, 2, 7, 2, 2, 2, 2, 2, 0, 2, 2, 2, 8, 2, 2, 
      2, 2, 9, 10, 6, 6, 11, 2, 1, 0, 3, 3, 3, 3, 3, 3, 
      3, 12, 12, 12, 13, 13, 13, 13, 6, 6, 8, 6, 0, 11, 14, 6, 
      6, 0, 15, 6, 
    };
}
}
