/* This file was generated by SableCC (http://www.sablecc.org/). */

using System;
using System.Collections;
using System.Text;

using  CardLang.analysis;

namespace CardLang.node {

public abstract class PProgram : Node
{
}

public abstract class PCard : Node
{
}

public abstract class PStatement : Node
{
}

public abstract class PExpression : Node
{
}


public sealed class AProgramProgram : PProgram
{
    private TypedList _card_;

    public AProgramProgram ()
    {
        this._card_ = new TypedList(new Card_Cast(this));
    }

    public AProgramProgram (
            IList _card_
    )
    {
        this._card_ = new TypedList(new Card_Cast(this));
        this._card_.Clear();
        this._card_.AddAll(_card_);
    }

    public override Object Clone()
    {
        return new AProgramProgram (
            CloneList (_card_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAProgramProgram(this);
    }

    public IList GetCard ()
    {
        return _card_;
    }

    public void setCard (IList list)
    {
        _card_.Clear();
        _card_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_card_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _card_.Contains(child) )
        {
            _card_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        for ( int i = 0; i < _card_.Count; i++ )
        {
            Node n = (Node)_card_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _card_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _card_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Card_Cast : Cast
    {
        AProgramProgram obj;

        internal Card_Cast (AProgramProgram obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PCard node = (PCard) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PCard node = (PCard) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AStatementCard : PCard
{
    private TypedList _identifier_;
    private TypedList _statement_;

    public AStatementCard ()
    {
        this._identifier_ = new TypedList(new Identifier_Cast(this));
        this._statement_ = new TypedList(new Statement_Cast(this));
    }

    public AStatementCard (
            IList _identifier_,
            IList _statement_
    )
    {
        this._identifier_ = new TypedList(new Identifier_Cast(this));
        this._identifier_.Clear();
        this._identifier_.AddAll(_identifier_);
        this._statement_ = new TypedList(new Statement_Cast(this));
        this._statement_.Clear();
        this._statement_.AddAll(_statement_);
    }

    public override Object Clone()
    {
        return new AStatementCard (
            CloneList (_identifier_),
            CloneList (_statement_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAStatementCard(this);
    }

    public IList GetIdentifier ()
    {
        return _identifier_;
    }

    public void setIdentifier (IList list)
    {
        _identifier_.Clear();
        _identifier_.AddAll(list);
    }
    public IList GetStatement ()
    {
        return _statement_;
    }

    public void setStatement (IList list)
    {
        _statement_.Clear();
        _statement_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_identifier_)
            + ToString (_statement_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _identifier_.Contains(child) )
        {
            _identifier_.Remove(child);
            return;
        }
        if ( _statement_.Contains(child) )
        {
            _statement_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        for ( int i = 0; i < _identifier_.Count; i++ )
        {
            Node n = (Node)_identifier_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _identifier_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _identifier_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
        for ( int i = 0; i < _statement_.Count; i++ )
        {
            Node n = (Node)_statement_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _statement_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _statement_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Identifier_Cast : Cast
    {
        AStatementCard obj;

        internal Identifier_Cast (AStatementCard obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            TIdentifier node = (TIdentifier) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            TIdentifier node = (TIdentifier) o;
            node.Parent(null);
            return node;
        }
    }
    private class Statement_Cast : Cast
    {
        AStatementCard obj;

        internal Statement_Cast (AStatementCard obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AReturnCard : PCard
{
    private TypedList _identifier_;
    private PExpression _expression_;

    public AReturnCard ()
    {
        this._identifier_ = new TypedList(new Identifier_Cast(this));
    }

    public AReturnCard (
            IList _identifier_,
            PExpression _expression_
    )
    {
        this._identifier_ = new TypedList(new Identifier_Cast(this));
        this._identifier_.Clear();
        this._identifier_.AddAll(_identifier_);
        SetExpression (_expression_);
    }

    public override Object Clone()
    {
        return new AReturnCard (
            CloneList (_identifier_),
            (PExpression)CloneNode (_expression_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAReturnCard(this);
    }

    public IList GetIdentifier ()
    {
        return _identifier_;
    }

    public void setIdentifier (IList list)
    {
        _identifier_.Clear();
        _identifier_.AddAll(list);
    }
    public PExpression GetExpression ()
    {
        return _expression_;
    }

    public void SetExpression (PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _expression_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_identifier_)
            + ToString (_expression_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _identifier_.Contains(child) )
        {
            _identifier_.Remove(child);
            return;
        }
        if ( _expression_ == child )
        {
            _expression_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        for ( int i = 0; i < _identifier_.Count; i++ )
        {
            Node n = (Node)_identifier_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _identifier_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _identifier_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
        if ( _expression_ == oldChild )
        {
            SetExpression ((PExpression) newChild);
            return;
        }
    }

    private class Identifier_Cast : Cast
    {
        AReturnCard obj;

        internal Identifier_Cast (AReturnCard obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            TIdentifier node = (TIdentifier) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            TIdentifier node = (TIdentifier) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AStopCard : PCard
{


    public AStopCard (
    )
    {
    }

    public override Object Clone()
    {
        return new AStopCard (
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAStopCard(this);
    }


    public override string ToString()
    {
        return ""
        ;
    }

    internal override void RemoveChild(Node child)
    {
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
    }

}
public sealed class AExpressionCard : PCard
{
    private PExpression _expression_;

    public AExpressionCard ()
    {
    }

    public AExpressionCard (
            PExpression _expression_
    )
    {
        SetExpression (_expression_);
    }

    public override Object Clone()
    {
        return new AExpressionCard (
            (PExpression)CloneNode (_expression_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAExpressionCard(this);
    }

    public PExpression GetExpression ()
    {
        return _expression_;
    }

    public void SetExpression (PExpression node)
    {
        if(_expression_ != null)
        {
            _expression_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _expression_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_expression_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _expression_ == child )
        {
            _expression_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _expression_ == oldChild )
        {
            SetExpression ((PExpression) newChild);
            return;
        }
    }

}
public sealed class AIfStatement : PStatement
{
    private PExpression _condition_;
    private TypedList _then_;

    public AIfStatement ()
    {
        this._then_ = new TypedList(new Then_Cast(this));
    }

    public AIfStatement (
            PExpression _condition_,
            IList _then_
    )
    {
        SetCondition (_condition_);
        this._then_ = new TypedList(new Then_Cast(this));
        this._then_.Clear();
        this._then_.AddAll(_then_);
    }

    public override Object Clone()
    {
        return new AIfStatement (
            (PExpression)CloneNode (_condition_),
            CloneList (_then_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAIfStatement(this);
    }

    public PExpression GetCondition ()
    {
        return _condition_;
    }

    public void SetCondition (PExpression node)
    {
        if(_condition_ != null)
        {
            _condition_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _condition_ = node;
    }
    public IList GetThen ()
    {
        return _then_;
    }

    public void setThen (IList list)
    {
        _then_.Clear();
        _then_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_condition_)
            + ToString (_then_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _condition_ == child )
        {
            _condition_ = null;
            return;
        }
        if ( _then_.Contains(child) )
        {
            _then_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _condition_ == oldChild )
        {
            SetCondition ((PExpression) newChild);
            return;
        }
        for ( int i = 0; i < _then_.Count; i++ )
        {
            Node n = (Node)_then_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _then_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _then_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Then_Cast : Cast
    {
        AIfStatement obj;

        internal Then_Cast (AIfStatement obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AIfElseStatement : PStatement
{
    private PExpression _condition_;
    private TypedList _then_;
    private TypedList _else_;

    public AIfElseStatement ()
    {
        this._then_ = new TypedList(new Then_Cast(this));
        this._else_ = new TypedList(new Else_Cast(this));
    }

    public AIfElseStatement (
            PExpression _condition_,
            IList _then_,
            IList _else_
    )
    {
        SetCondition (_condition_);
        this._then_ = new TypedList(new Then_Cast(this));
        this._then_.Clear();
        this._then_.AddAll(_then_);
        this._else_ = new TypedList(new Else_Cast(this));
        this._else_.Clear();
        this._else_.AddAll(_else_);
    }

    public override Object Clone()
    {
        return new AIfElseStatement (
            (PExpression)CloneNode (_condition_),
            CloneList (_then_),
            CloneList (_else_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAIfElseStatement(this);
    }

    public PExpression GetCondition ()
    {
        return _condition_;
    }

    public void SetCondition (PExpression node)
    {
        if(_condition_ != null)
        {
            _condition_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _condition_ = node;
    }
    public IList GetThen ()
    {
        return _then_;
    }

    public void setThen (IList list)
    {
        _then_.Clear();
        _then_.AddAll(list);
    }
    public IList GetElse ()
    {
        return _else_;
    }

    public void setElse (IList list)
    {
        _else_.Clear();
        _else_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_condition_)
            + ToString (_then_)
            + ToString (_else_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _condition_ == child )
        {
            _condition_ = null;
            return;
        }
        if ( _then_.Contains(child) )
        {
            _then_.Remove(child);
            return;
        }
        if ( _else_.Contains(child) )
        {
            _else_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _condition_ == oldChild )
        {
            SetCondition ((PExpression) newChild);
            return;
        }
        for ( int i = 0; i < _then_.Count; i++ )
        {
            Node n = (Node)_then_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _then_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _then_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
        for ( int i = 0; i < _else_.Count; i++ )
        {
            Node n = (Node)_else_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _else_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _else_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Then_Cast : Cast
    {
        AIfElseStatement obj;

        internal Then_Cast (AIfElseStatement obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
    private class Else_Cast : Cast
    {
        AIfElseStatement obj;

        internal Else_Cast (AIfElseStatement obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class AWhileStatement : PStatement
{
    private PExpression _condition_;
    private TypedList _do_;

    public AWhileStatement ()
    {
        this._do_ = new TypedList(new Do_Cast(this));
    }

    public AWhileStatement (
            PExpression _condition_,
            IList _do_
    )
    {
        SetCondition (_condition_);
        this._do_ = new TypedList(new Do_Cast(this));
        this._do_.Clear();
        this._do_.AddAll(_do_);
    }

    public override Object Clone()
    {
        return new AWhileStatement (
            (PExpression)CloneNode (_condition_),
            CloneList (_do_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAWhileStatement(this);
    }

    public PExpression GetCondition ()
    {
        return _condition_;
    }

    public void SetCondition (PExpression node)
    {
        if(_condition_ != null)
        {
            _condition_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _condition_ = node;
    }
    public IList GetDo ()
    {
        return _do_;
    }

    public void setDo (IList list)
    {
        _do_.Clear();
        _do_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_condition_)
            + ToString (_do_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _condition_ == child )
        {
            _condition_ = null;
            return;
        }
        if ( _do_.Contains(child) )
        {
            _do_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _condition_ == oldChild )
        {
            SetCondition ((PExpression) newChild);
            return;
        }
        for ( int i = 0; i < _do_.Count; i++ )
        {
            Node n = (Node)_do_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _do_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _do_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Do_Cast : Cast
    {
        AWhileStatement obj;

        internal Do_Cast (AWhileStatement obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class ARepeatStatement : PStatement
{
    private PExpression _times_;
    private TypedList _do_;

    public ARepeatStatement ()
    {
        this._do_ = new TypedList(new Do_Cast(this));
    }

    public ARepeatStatement (
            PExpression _times_,
            IList _do_
    )
    {
        SetTimes (_times_);
        this._do_ = new TypedList(new Do_Cast(this));
        this._do_.Clear();
        this._do_.AddAll(_do_);
    }

    public override Object Clone()
    {
        return new ARepeatStatement (
            (PExpression)CloneNode (_times_),
            CloneList (_do_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseARepeatStatement(this);
    }

    public PExpression GetTimes ()
    {
        return _times_;
    }

    public void SetTimes (PExpression node)
    {
        if(_times_ != null)
        {
            _times_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _times_ = node;
    }
    public IList GetDo ()
    {
        return _do_;
    }

    public void setDo (IList list)
    {
        _do_.Clear();
        _do_.AddAll(list);
    }

    public override string ToString()
    {
        return ""
            + ToString (_times_)
            + ToString (_do_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _times_ == child )
        {
            _times_ = null;
            return;
        }
        if ( _do_.Contains(child) )
        {
            _do_.Remove(child);
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _times_ == oldChild )
        {
            SetTimes ((PExpression) newChild);
            return;
        }
        for ( int i = 0; i < _do_.Count; i++ )
        {
            Node n = (Node)_do_[i];
            if(n == oldChild)
            {
                if(newChild != null)
                {
                    _do_[i] = newChild;
                    oldChild.Parent(null);
                    return;
                }

                _do_.RemoveAt(i);
                oldChild.Parent(null);
                return;
            }
        }
    }

    private class Do_Cast : Cast
    {
        ARepeatStatement obj;

        internal Do_Cast (ARepeatStatement obj)
        {
          this.obj = obj;
        }

        public Object Cast(Object o)
        {
            PStatement node = (PStatement) o;

            if((node.Parent() != null) &&
                (node.Parent() != obj))
            {
                node.Parent().RemoveChild(node);
            }

            if((node.Parent() == null) ||
                (node.Parent() != obj))
            {
                node.Parent(obj);
            }

            return node;
        }

        public Object UnCast(Object o)
        {
            PStatement node = (PStatement) o;
            node.Parent(null);
            return node;
        }
    }
}
public sealed class ADamageStatement : PStatement
{
    private PExpression _amount_;

    public ADamageStatement ()
    {
    }

    public ADamageStatement (
            PExpression _amount_
    )
    {
        SetAmount (_amount_);
    }

    public override Object Clone()
    {
        return new ADamageStatement (
            (PExpression)CloneNode (_amount_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseADamageStatement(this);
    }

    public PExpression GetAmount ()
    {
        return _amount_;
    }

    public void SetAmount (PExpression node)
    {
        if(_amount_ != null)
        {
            _amount_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _amount_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_amount_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _amount_ == child )
        {
            _amount_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _amount_ == oldChild )
        {
            SetAmount ((PExpression) newChild);
            return;
        }
    }

}
public sealed class AHealStatement : PStatement
{
    private PExpression _amount_;

    public AHealStatement ()
    {
    }

    public AHealStatement (
            PExpression _amount_
    )
    {
        SetAmount (_amount_);
    }

    public override Object Clone()
    {
        return new AHealStatement (
            (PExpression)CloneNode (_amount_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAHealStatement(this);
    }

    public PExpression GetAmount ()
    {
        return _amount_;
    }

    public void SetAmount (PExpression node)
    {
        if(_amount_ != null)
        {
            _amount_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _amount_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_amount_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _amount_ == child )
        {
            _amount_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _amount_ == oldChild )
        {
            SetAmount ((PExpression) newChild);
            return;
        }
    }

}
public sealed class APullStatement : PStatement
{
    private PExpression _amount_;

    public APullStatement ()
    {
    }

    public APullStatement (
            PExpression _amount_
    )
    {
        SetAmount (_amount_);
    }

    public override Object Clone()
    {
        return new APullStatement (
            (PExpression)CloneNode (_amount_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAPullStatement(this);
    }

    public PExpression GetAmount ()
    {
        return _amount_;
    }

    public void SetAmount (PExpression node)
    {
        if(_amount_ != null)
        {
            _amount_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _amount_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_amount_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _amount_ == child )
        {
            _amount_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _amount_ == oldChild )
        {
            SetAmount ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ARechargeStatement : PStatement
{
    private PExpression _amount_;

    public ARechargeStatement ()
    {
    }

    public ARechargeStatement (
            PExpression _amount_
    )
    {
        SetAmount (_amount_);
    }

    public override Object Clone()
    {
        return new ARechargeStatement (
            (PExpression)CloneNode (_amount_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseARechargeStatement(this);
    }

    public PExpression GetAmount ()
    {
        return _amount_;
    }

    public void SetAmount (PExpression node)
    {
        if(_amount_ != null)
        {
            _amount_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _amount_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_amount_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _amount_ == child )
        {
            _amount_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _amount_ == oldChild )
        {
            SetAmount ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ARunStatement : PStatement
{
    private TName _name_;

    public ARunStatement ()
    {
    }

    public ARunStatement (
            TName _name_
    )
    {
        SetName (_name_);
    }

    public override Object Clone()
    {
        return new ARunStatement (
            (TName)CloneNode (_name_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseARunStatement(this);
    }

    public TName GetName ()
    {
        return _name_;
    }

    public void SetName (TName node)
    {
        if(_name_ != null)
        {
            _name_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _name_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_name_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _name_ == child )
        {
            _name_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _name_ == oldChild )
        {
            SetName ((TName) newChild);
            return;
        }
    }

}
public sealed class AInsertStatement : PStatement
{
    private TIdentifier _name_;

    public AInsertStatement ()
    {
    }

    public AInsertStatement (
            TIdentifier _name_
    )
    {
        SetName (_name_);
    }

    public override Object Clone()
    {
        return new AInsertStatement (
            (TIdentifier)CloneNode (_name_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAInsertStatement(this);
    }

    public TIdentifier GetName ()
    {
        return _name_;
    }

    public void SetName (TIdentifier node)
    {
        if(_name_ != null)
        {
            _name_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _name_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_name_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _name_ == child )
        {
            _name_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _name_ == oldChild )
        {
            SetName ((TIdentifier) newChild);
            return;
        }
    }

}
public sealed class AAddExpression : PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public AAddExpression ()
    {
    }

    public AAddExpression (
            PExpression _left_,
            PExpression _right_
    )
    {
        SetLeft (_left_);
        SetRight (_right_);
    }

    public override Object Clone()
    {
        return new AAddExpression (
            (PExpression)CloneNode (_left_),
            (PExpression)CloneNode (_right_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAAddExpression(this);
    }

    public PExpression GetLeft ()
    {
        return _left_;
    }

    public void SetLeft (PExpression node)
    {
        if(_left_ != null)
        {
            _left_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _left_ = node;
    }
    public PExpression GetRight ()
    {
        return _right_;
    }

    public void SetRight (PExpression node)
    {
        if(_right_ != null)
        {
            _right_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _right_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_left_)
            + ToString (_right_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _left_ == child )
        {
            _left_ = null;
            return;
        }
        if ( _right_ == child )
        {
            _right_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _left_ == oldChild )
        {
            SetLeft ((PExpression) newChild);
            return;
        }
        if ( _right_ == oldChild )
        {
            SetRight ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ASubExpression : PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public ASubExpression ()
    {
    }

    public ASubExpression (
            PExpression _left_,
            PExpression _right_
    )
    {
        SetLeft (_left_);
        SetRight (_right_);
    }

    public override Object Clone()
    {
        return new ASubExpression (
            (PExpression)CloneNode (_left_),
            (PExpression)CloneNode (_right_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseASubExpression(this);
    }

    public PExpression GetLeft ()
    {
        return _left_;
    }

    public void SetLeft (PExpression node)
    {
        if(_left_ != null)
        {
            _left_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _left_ = node;
    }
    public PExpression GetRight ()
    {
        return _right_;
    }

    public void SetRight (PExpression node)
    {
        if(_right_ != null)
        {
            _right_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _right_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_left_)
            + ToString (_right_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _left_ == child )
        {
            _left_ = null;
            return;
        }
        if ( _right_ == child )
        {
            _right_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _left_ == oldChild )
        {
            SetLeft ((PExpression) newChild);
            return;
        }
        if ( _right_ == oldChild )
        {
            SetRight ((PExpression) newChild);
            return;
        }
    }

}
public sealed class AMulExpression : PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public AMulExpression ()
    {
    }

    public AMulExpression (
            PExpression _left_,
            PExpression _right_
    )
    {
        SetLeft (_left_);
        SetRight (_right_);
    }

    public override Object Clone()
    {
        return new AMulExpression (
            (PExpression)CloneNode (_left_),
            (PExpression)CloneNode (_right_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAMulExpression(this);
    }

    public PExpression GetLeft ()
    {
        return _left_;
    }

    public void SetLeft (PExpression node)
    {
        if(_left_ != null)
        {
            _left_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _left_ = node;
    }
    public PExpression GetRight ()
    {
        return _right_;
    }

    public void SetRight (PExpression node)
    {
        if(_right_ != null)
        {
            _right_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _right_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_left_)
            + ToString (_right_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _left_ == child )
        {
            _left_ = null;
            return;
        }
        if ( _right_ == child )
        {
            _right_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _left_ == oldChild )
        {
            SetLeft ((PExpression) newChild);
            return;
        }
        if ( _right_ == oldChild )
        {
            SetRight ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ADivExpression : PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public ADivExpression ()
    {
    }

    public ADivExpression (
            PExpression _left_,
            PExpression _right_
    )
    {
        SetLeft (_left_);
        SetRight (_right_);
    }

    public override Object Clone()
    {
        return new ADivExpression (
            (PExpression)CloneNode (_left_),
            (PExpression)CloneNode (_right_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseADivExpression(this);
    }

    public PExpression GetLeft ()
    {
        return _left_;
    }

    public void SetLeft (PExpression node)
    {
        if(_left_ != null)
        {
            _left_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _left_ = node;
    }
    public PExpression GetRight ()
    {
        return _right_;
    }

    public void SetRight (PExpression node)
    {
        if(_right_ != null)
        {
            _right_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _right_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_left_)
            + ToString (_right_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _left_ == child )
        {
            _left_ = null;
            return;
        }
        if ( _right_ == child )
        {
            _right_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _left_ == oldChild )
        {
            SetLeft ((PExpression) newChild);
            return;
        }
        if ( _right_ == oldChild )
        {
            SetRight ((PExpression) newChild);
            return;
        }
    }

}
public sealed class AModExpression : PExpression
{
    private PExpression _left_;
    private PExpression _right_;

    public AModExpression ()
    {
    }

    public AModExpression (
            PExpression _left_,
            PExpression _right_
    )
    {
        SetLeft (_left_);
        SetRight (_right_);
    }

    public override Object Clone()
    {
        return new AModExpression (
            (PExpression)CloneNode (_left_),
            (PExpression)CloneNode (_right_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAModExpression(this);
    }

    public PExpression GetLeft ()
    {
        return _left_;
    }

    public void SetLeft (PExpression node)
    {
        if(_left_ != null)
        {
            _left_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _left_ = node;
    }
    public PExpression GetRight ()
    {
        return _right_;
    }

    public void SetRight (PExpression node)
    {
        if(_right_ != null)
        {
            _right_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _right_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_left_)
            + ToString (_right_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _left_ == child )
        {
            _left_ = null;
            return;
        }
        if ( _right_ == child )
        {
            _right_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _left_ == oldChild )
        {
            SetLeft ((PExpression) newChild);
            return;
        }
        if ( _right_ == oldChild )
        {
            SetRight ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ARandomExpression : PExpression
{
    private PExpression _min_;
    private PExpression _max_;

    public ARandomExpression ()
    {
    }

    public ARandomExpression (
            PExpression _min_,
            PExpression _max_
    )
    {
        SetMin (_min_);
        SetMax (_max_);
    }

    public override Object Clone()
    {
        return new ARandomExpression (
            (PExpression)CloneNode (_min_),
            (PExpression)CloneNode (_max_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseARandomExpression(this);
    }

    public PExpression GetMin ()
    {
        return _min_;
    }

    public void SetMin (PExpression node)
    {
        if(_min_ != null)
        {
            _min_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _min_ = node;
    }
    public PExpression GetMax ()
    {
        return _max_;
    }

    public void SetMax (PExpression node)
    {
        if(_max_ != null)
        {
            _max_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _max_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_min_)
            + ToString (_max_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _min_ == child )
        {
            _min_ = null;
            return;
        }
        if ( _max_ == child )
        {
            _max_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _min_ == oldChild )
        {
            SetMin ((PExpression) newChild);
            return;
        }
        if ( _max_ == oldChild )
        {
            SetMax ((PExpression) newChild);
            return;
        }
    }

}
public sealed class ANumberExpression : PExpression
{
    private TNumber _value_;

    public ANumberExpression ()
    {
    }

    public ANumberExpression (
            TNumber _value_
    )
    {
        SetValue (_value_);
    }

    public override Object Clone()
    {
        return new ANumberExpression (
            (TNumber)CloneNode (_value_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseANumberExpression(this);
    }

    public TNumber GetValue ()
    {
        return _value_;
    }

    public void SetValue (TNumber node)
    {
        if(_value_ != null)
        {
            _value_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _value_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_value_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _value_ == child )
        {
            _value_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _value_ == oldChild )
        {
            SetValue ((TNumber) newChild);
            return;
        }
    }

}
public sealed class AIdentifierExpression : PExpression
{
    private TIdentifier _name_;

    public AIdentifierExpression ()
    {
    }

    public AIdentifierExpression (
            TIdentifier _name_
    )
    {
        SetName (_name_);
    }

    public override Object Clone()
    {
        return new AIdentifierExpression (
            (TIdentifier)CloneNode (_name_)
        );
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseAIdentifierExpression(this);
    }

    public TIdentifier GetName ()
    {
        return _name_;
    }

    public void SetName (TIdentifier node)
    {
        if(_name_ != null)
        {
            _name_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _name_ = node;
    }

    public override string ToString()
    {
        return ""
            + ToString (_name_)
        ;
    }

    internal override void RemoveChild(Node child)
    {
        if ( _name_ == child )
        {
            _name_ = null;
            return;
        }
    }

    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if ( _name_ == oldChild )
        {
            SetName ((TIdentifier) newChild);
            return;
        }
    }

}

public sealed class Start : Node
{
    private PProgram _base_;
    private EOF _eof_;

    public Start()
    {
    }

    public Start(
        PProgram _base_,
        EOF _eof_)
    {
        SetPProgram(_base_);
        SetEOF(_eof_);
    }

    public override Object Clone()
    {
        return new Start(
            (PProgram) CloneNode(_base_),
            (EOF) CloneNode(_eof_));
    }

    public override void Apply(Switch sw)
    {
        ((Analysis) sw).CaseStart(this);
    }

    public PProgram GetPProgram()
    {
        return _base_;
    }
    public void SetPProgram(PProgram node)
    {
        if(_base_ != null)
        {
            _base_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _base_ = node;
    }

    public EOF GetEOF()
    {
        return _eof_;
    }
    public void SetEOF(EOF node)
    {
        if(_eof_ != null)
        {
            _eof_.Parent(null);
        }

        if(node != null)
        {
            if(node.Parent() != null)
            {
                node.Parent().RemoveChild(node);
            }

            node.Parent(this);
        }

        _eof_ = node;
    }

    internal override void RemoveChild(Node child)
    {
        if(_base_ == child)
        {
            _base_ = null;
            return;
        }

        if(_eof_ == child)
        {
            _eof_ = null;
            return;
        }
    }
    internal override void ReplaceChild(Node oldChild, Node newChild)
    {
        if(_base_ == oldChild)
        {
            SetPProgram((PProgram) newChild);
            return;
        }

        if(_eof_ == oldChild)
        {
            SetEOF((EOF) newChild);
            return;
        }
    }

    public override string ToString()
    {
        return "" +
            ToString(_base_) +
            ToString(_eof_);
    }
}
}
